// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Las migraciones van por la conexión DIRECTA: a través del pooler de
    // Neon (pgbouncer) el advisory lock de Prisma puede colgarse → P1002.
    // El runtime de la app sigue usando DATABASE_URL (pooleada) vía adapter.
    url: process.env["DATABASE_URL_UNPOOLED"] || process.env["DATABASE_URL"],
  },
});
